### ISSUE TITLE
simBarcode

### ISSUE THREAD

**Issue by zarubto4** [lucamora/tmclient#1]
Hello, whare is in documentation simBarcode? Its required for "Activate Sim" Request, but in official documentation in PDF is only one word and its only that its required for request. Thx.

**Comment by lucamora** [comment]
@zarubto4 sorry for the delayed answer but I have disabled the notifications since I'm not actively working on this repo (maybe in the next months I will update the module to support the new API version).
I'm not sure that I understand your question... are you asking where you can find the simBarcode?
`simBarcode` is the *ICCID* of the SIM (or *SIM Card Identifier*) that you can find on the back of the SIM card [official documentation](https://www.thingsmobile.com/activate).
It is useful only during the activation process.
